### ISSUE TITLE
TODO: Commands (slash commands too) errors won't stop event loop

### ISSUE THREAD

**Issue by Jerry-py** [EpikCord/EpikCord.py#102]
### Summary

Continue event loop when command raises error

### The Problem

The commands errors including slash commands raising error will stop event so we want to implement this

### The Ideal Solution

Make the event loop continue

### The Current Solution

@TheUntraceable has it (I think)

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] Full details of the requested feature have been provided/shown

**Comment by TheUntraceable** [comment]
Add try excepts.

**Comment by Jerry-py** [comment]
Fixed: https://github.com/EpikCord/EpikCord.py/commit/7a8fbb5a19b92aeadc63d5312bd3bbdf56931460
