### ISSUE TITLE
pip not recognising changes in code if there is no version bump

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#109]
### Summary

pip not recognising changes in code if there is no version bump

### Reproduction Steps

Type this in terminal
```shell
py -3.10 -m pip install git+https://github.com/EpikCord/EpikCord.py
```

then make a change in library and type the above line in terminal

### Expected Results

updates lib

### Actual Results

doesnt update lib

### Intents

not important

### System Information

not important

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

### Additional Context

there are 2 ways first is to bump the version and the other is to use `--force-reinstall` flag

**Comment by Jerry-py** [comment]
See more here https://jerrydotpy.github.io/EpikCordGuide/

**Comment by TheUntraceable** [comment]
I'm aware of this and this is expected behaviour of Pip. I will be bumping the version accordingly.
