### ISSUE TITLE
Heartbeating

### ISSUE THREAD

**Issue by TheUntraceable** [EpikCord/EpikCord.py#114]
### Summary

Heartbeating is weird, don't know where to put it.

### Reproduction Steps

Literally no bot will last more than `Client.interval`

### Minimal Reproducible Code

```python
Client(token, intents).login()
```

### Expected Results

The bot to run ***forever***

### Actual Results

Crashes with a code 1000

### Intents

Irrelevant

### System Information

Latest build

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

### Additional Context

ASAP NEEDS FIXING

**Comment by Jerry-py** [comment]
We need a heartbeat limit

**Comment by Jerry-py** [comment]
Like 10 per minute

**Comment by TheUntraceable** [comment]
The interval is 41.25 seconds... can't really do 10 per minute if that's the interval.

**Comment by Jerry-py** [comment]
Thats discord.py limit

**Comment by TheUntraceable** [comment]
I guess they changed the heartbeat interval from something small.

**Comment by TheUntraceable** [comment]
I think I figured it out. Testing and *should* be fixed in 2 hours ish
