### ISSUE TITLE
Connection closes with code NONE

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#121]
### Summary

EpikCord.ClosedWebSocketConnection: Connection has been closed with code None

### Reproduction Steps

run bot.

I have diagnosed it to be on the commit #aa8dac5

I strongly recommend reverting the commit 

### Expected Results

bot to start

### Actual Results

Task exception was never retrieved
future: <Task finished name='Task-4' coro=<EventHandler.handle_events() done, defined at C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EpikCord\__init__.py:625> exception=ClosedWebSocketConnection('Connection has been closed with code None')>
Traceback (most recent call last):
  File "C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EpikCord\__init__.py", line 671, in handle_events
    await self.handle_close()
  File "C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\EpikCord\__init__.py", line 980, in handle_close
    raise ClosedWebSocketConnection(f"Connection has been closed with code {self.ws.close_code}")
EpikCord.ClosedWebSocketConnection: Connection has been closed with code None

### Intents

not important

### System Information

recent commit

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

**Comment by Jerry-py** [comment]
`self.ws.close_code` is returning None because their isn't a error code so I'm guessing simple solution: `if self.ws.close_code == 
None: ...`

**Comment by nav-github01001** [comment]
> `self.ws.close_code` is returning None because their isn't a error code so I'm guessing simple solution: `if self.ws.close_code == None: ...`

it is fixed in #120

**Comment by TheUntraceable** [comment]
> `self.ws.close_code` is returning None because their isn't a error code so I'm guessing simple solution: `if self.ws.close_code == None: ...`

There should always be a close code otherwise the `handle_close` event is NEVER called, which is the only function which uses the `close_code`. I looked into the source for `__aiter__` in `ClientWebsocketResponse` and it stops the iteraction whenever it's a `Closing Code Message`

**Comment by nav-github01001** [comment]
solved in #120
