### ISSUE TITLE
Intents being weird

### ISSUE THREAD

**Issue by TheUntraceable** [EpikCord/EpikCord.py#126]
### Summary

The method for intents right now is messy.

### Reproduction Steps

Just use Intents.

### Minimal Reproducible Code

```python
intents = Intents.x.x.x.x.x.x
```

### Expected Results

For a cleaner syntax

### Actual Results

Looks like a *mess*

### Intents

haha ironic

### System Information

All versions including Intents

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

**Comment by ZenoABC** [comment]
`intents = Intents()`
`intents.something = True # to enable`
`intents.something = False # to disable`
Maybe, just maybe ?

**Comment by TheUntraceable** [comment]
Yeah exactly that

**Comment by ZenoABC** [comment]
Can PR that if you won't mind.

**Comment by TheUntraceable** [comment]
I was thinking of this for a long time, because of how permissions are going to be inconsistent with Intents and that'll be annoying, and it may be desirable to check if you have intents enabled

**Comment by TheUntraceable** [comment]
> Can PR that if you won't mind.

I don't mind 😄

**Comment by ZenoABC** [comment]
:+1:
