### ISSUE TITLE
:bug: Paginator index is not updating properly

### ISSUE THREAD

**Issue by Sigmanificient** [EpikCord/EpikCord.py#146]
### Summary

when using `paginator.forward()` & `paginator.back()`, the index is left unchanged

### Reproduction Steps

Follow the code below

### Minimal Reproducible Code

```python
from Epikcord import Embed, Paginator

pagninator = Paginator()
pagninator.add_page(Embed())

print(pagninator.current_index)
pagninator.forward()
print(pagninator.current_index)
```

### Expected Results

`current_index` should have been increased by one

### Actual Results

`current_index` stays the same

### Intents

None

### System Information

Any

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

**Comment by TheUntraceable** [comment]
I edited your Minimal Reproducable code to be correct, missed a "r".
