### ISSUE TITLE
Splitting of files

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#151]
### Summary

Note: this is a WiP, this issue is just to report progress

### The Problem

This method of stuffing code in __init__.py is very bad because it is 1) A big project and 2) Organization

### The Ideal Solution

Doit

### Additional Context

This undertaking is really hard and tedious because we need to not have Circular Import Errors

**Comment by nav-github01001** [comment]
@theuntraceable we can split the activity classes and those related to them

**Comment by nav-github01001** [comment]
@theuntraceable we can split the activity classes and those related to them

**Comment by TheUntraceable** [comment]
Yes, also any reason why your Github keeps sending the same message? Bad connection?

**Comment by nav-github01001** [comment]
Yeah indian Internet be like
