### ISSUE TITLE
Localisation Support

### ISSUE THREAD

**Issue by TheUntraceable** [EpikCord/EpikCord.py#157]
### Summary

Add support for Localisation of Application Commands.

### The Problem

There is no method of this.

### The Ideal Solution

For there to be added arguments to the command decorators.

**Comment by nav-github01001** [comment]
Which means what?

**Comment by TheUntraceable** [comment]
https://discord.com/developers/docs/interactions/application-commands#localization

**Comment by nav-github01001** [comment]
I think we need to have this attrib but convert it into utf-8 after

**Comment by TheUntraceable** [comment]
What does utf-8 have anything to do with this? Just add in a `Localisation` argument, which takes in a `Locale` and a name and description.
