### ISSUE TITLE
Support for AutoMod

### ISSUE THREAD

**Issue by TheUntraceable** [EpikCord/EpikCord.py#158]
### Summary

AutoMod is new, add support for it. 

### The Problem

There is a new feature, called Automod, we have no support for it as of now.

### The Ideal Solution

For an implementation of this to exist.

**Comment by ZenoABC** [comment]
Maybe work on library itself first ?

**Comment by ZenoABC** [comment]
Alright then, but work on core itself first before going on with automod.

**Comment by TheUntraceable** [comment]
What do you mean by "core"?

**Comment by ZenoABC** [comment]
HTTP, WS, Ratelimit, etc.. You know, essentials.

**Comment by TheUntraceable** [comment]
HTTP Routes, that's gonna be fun.
RateLimits, I think I can implement that now.
Events, Haha... moving on.

Yeah I guess you're right.
