### ISSUE TITLE
Flags

### ISSUE THREAD

**Issue by Jerry-py** [EpikCord/EpikCord.py#27]
## Description

Adding flags for 100% discord coverage

## The problem

No problem 

## The solution

None

## The current solution, if any

None

## Checklist

- [x] - You have checked that there is no issue already mentioning this feature, open or closed
- [x] - Full details of the requested feature have been provided/shown

**Comment by nav-github01001** [comment]
We are done flags

**Comment by nav-github01001** [comment]
Right
