### ISSUE TITLE
Fetching invite 

### ISSUE THREAD

**Issue by Jerry-py** [EpikCord/EpikCord.py#31]
## Description

Fetching invite 

## Checklist

- [x] - You have checked that there is no issue already mentioning this feature, open or closed
- [x] - Full details of the requested feature have been provided/shown

**Comment by TheUntraceable** [comment]
You mean `Guild.fetch_invite`? I think that method works

**Comment by TheUntraceable** [comment]
I clicked the wrong button, again...

**Comment by nav-github01001** [comment]
This is done

**Comment by TheUntraceable** [comment]
This issue is redundant. There are a million methods we are yet to implement, so if I kept this open, it may suggest that we need a reminder for each method.
