### ISSUE TITLE
Add `Logger` Feature

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#32]
## Description

logging helps a lot- it helps you see which event is fired

## The solution

Implement logger module

## Checklist

- [x] - You have checked that there is no issue already mentioning this feature, open or closed
- [x] - Full details of the requested feature have been provided/shown

**Comment by Jerry-py** [comment]
Logging would basically meaning we have to go through each function in the library and adding logging

**Comment by TheUntraceable** [comment]
Yeah I'll do this later.

**Comment by TheUntraceable** [comment]
I'll be working on this whilst I can.

**Comment by TheUntraceable** [comment]
Too tedious, someone else can try do this.

**Comment by Jerry-py** [comment]
Not me

**Comment by nav-github01001** [comment]
> Too tedious, someone else can try do this.

hey im doing this

**Comment by TheUntraceable** [comment]
Done this.
