### ISSUE TITLE
ISO8601 Implementation

### ISSUE THREAD

**Issue by TheUntraceable** [EpikCord/EpikCord.py#36]
## Description
So Discord make sue if the ISO8601 Date/Time thingy so I need to implement that.

## The problem
Dsicord uses this in the API for many different things. I don't and I shrug it off it being typehinted as a str.

## The solution
Implement this.

## The current solution, if any
None

## Checklist

- [x] - You have checked that there is no issue already mentioning this feature, open or closed
- [x] - Full details of the requested feature have been provided/shown

**Comment by TheUntraceable** [comment]
Using `json.loads` and `json.dumps` for a better understanding, the `loads` (parsing) of the ISO8601 is `datetime.datetime.fromisoformat`, and the `dumps` (encoding) of the ISO8601 is `datetime.datetime.isoformat()`

**Comment by TheUntraceable** [comment]
Will be doing in the rewrite.

**Comment by nav-github01001** [comment]
Isn't this solved alr

**Comment by TheUntraceable** [comment]
No
