### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by Jerry-py** [EpikCord/EpikCord.py#37]
## Description

Adding tasks to the lib 

## The problem

Having to implement a task loop by yourself

## The solution

Implement it

## Checklist

- [x] - You have checked that there is no issue already mentioning this feature, open or closed
- [x] - Full details of the requested feature have been provided/shown

**Comment by Jerry-py** [comment]
I can do this but right now I'm leave this open

**Comment by Jerry-py** [comment]
@TheUntraceable asign me on this issue

**Comment by itsnotrin** [comment]
Done @Jerry-py

**Comment by Jerrydotpy** [comment]
Uhh I feel like we can save this as a draft and this is kinda hard for me to do and I feel like I don't want to do this

**Comment by TheUntraceable** [comment]
I'll try to.

**Comment by TheUntraceable** [comment]
What are these meant to be?

**Comment by nav-github01001** [comment]
Will be doing this after 10th may

**Comment by TheUntraceable** [comment]
It's 19th of July.

**Comment by nav-github01001** [comment]
Oof 10th july

**Comment by nav-github01001** [comment]
> It's 19th of July.

June

**Comment by TheUntraceable** [comment]
Right. Forgot about that, just woke up.

**Comment by TheUntraceable** [comment]
Is this meant to be like `discord.ext.tasks`?

**Comment by nav-github01001** [comment]
Nah. Just an integration on Clent or Smith.lemme check d.py code

**Comment by TheUntraceable** [comment]
What, I don't get what this PR is for. asyncio.Task??

**Comment by nav-github01001** [comment]
So basically it is for the background tasks 4 the bot 4 example 
```python
@task
def get_bot_shard_perf():
    for shard in client.shards:
         ...


Client.register_task(get_bot_shard_perf)

```

**Comment by TheUntraceable** [comment]
And run the task how many times?

**Comment by nav-github01001** [comment]
N number of times until bot dies.
The task starts after bot starts or respective Cog starts

**Comment by nav-github01001** [comment]
Oof sections

**Comment by TheUntraceable** [comment]
That's not smart, if they make an API call.... From what you're telling me this is exactly like `discord.ext.tasks`

**Comment by nav-github01001** [comment]
> That's not smart, if they make an API call.... From what you're telling me this is exactly like `discord.ext.tasks`

You may add an attribute which sets the no of times and delays.

**Comment by ZenoABC** [comment]
What is this meant for ?

**Comment by nav-github01001** [comment]
Api call to their own website for shard info ok but I see your concern abt the discord API calls, but that is why you have to_discord flag in HTTPclient

**Comment by ZenoABC** [comment]
That is like `discord.ext.tasks` then.

**Comment by nav-github01001** [comment]
> 

That is why Mr Jerry made this issue

**Comment by ZenoABC** [comment]
Does not explain why, but ok.

**Comment by ZenoABC** [comment]
Anyway, it makes sense to have something similiar to `discord.ext.tasks` as some people will need it for repeating task.

**Comment by nav-github01001** [comment]
> Does not explain why, but ok.

Look if you have to have a 4ever running task but without calling a command

**Comment by ZenoABC** [comment]
> > Does not explain why, but ok.
> 
> Look if you have to have a 4ever running task but without calling a command

Yeah i already said it makes sense to have one in library.

**Comment by nav-github01001** [comment]
> Is this meant to be like `discord.ext.tasks`?

I meant that it is not an extension and just an integration to client

**Comment by ZenoABC** [comment]
> > Is this meant to be like `discord.ext.tasks`?
> 
> I meant that it is not an extension and just an integration to client

I am saying, is it fundamentally similiar to `discord.ext.tasks` ?

**Comment by nav-github01001** [comment]
It is

**Comment by ZenoABC** [comment]
That's what i meant.
