### ISSUE TITLE
Ratelimit Handler

### ISSUE THREAD

**Issue by TheUntraceable** [EpikCord/EpikCord.py#4]
We need to implement a rate limit handler.

**Comment by Jerry-py** [comment]
I'm guessing there has to be heartbeat count and per (time) and we calculate using `time.time` e.g. `if time > ... : return false`

**Comment by TheUntraceable** [comment]
Calculate what? All I do to heartbeat is a simple ```py
await self.ws.send_json({"op": self.HEARTBEAT, "s": self.sequence})

**Comment by Jerry-py** [comment]
Alr

**Comment by TheUntraceable** [comment]
I closed the wrong issue 🤦

**Comment by TheUntraceable** [comment]
Will be handling this.

**Comment by Jerry-py** [comment]
Shouldn't be too hard right?

**Comment by TheUntraceable** [comment]
Nope, just need to add a few things to the `RatelimitHandler` and `HTTPClient`.

**Comment by nav-github01001** [comment]
Done this?

**Comment by TheUntraceable** [comment]
Nope...

**Comment by nav-github01001** [comment]
:/

**Comment by TheUntraceable** [comment]
There are current a few API calls with major parameters which I need to change to explicitly give in the `X_id`
5 in  Guild
5 in GuildChannel
3 in Messageable
6 in GuildTextChannel
1 in GuildNewsChannel

**Comment by nav-github01001** [comment]
We did it
