### ISSUE TITLE
Dict[KEY] instead of Dict.get()

### ISSUE THREAD

**Issue by TheUntraceable** [EpikCord/EpikCord.py#43]
### Summary

I used the incorrect method to get the value of a key from the data dict.

### Reproduction Steps

Literally anything.

### Minimal Reproducible Code

```python
Anything.
```

### Expected Results

No errors to be thrown

### Actual Results

Errors are thrown

### Intents

All.

### System Information

It won't run on anything.

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

### Additional Context

I need to replace all mentions of dict[key] with dict.get(key) to suppress KeyErrors.

**Comment by Jerry-py** [comment]
Does this count with `__init__ functions` like `Message.__init__`

**Comment by Jerry-py** [comment]
Whoops

**Comment by Jerry-py** [comment]
I read it backwards so ye

**Comment by Jerry-py** [comment]
Ignore the commit

**Comment by nav-github01001** [comment]
solved in #49

**Comment by Jerry-py** [comment]
Close bc finished

**Comment by nav-github01001** [comment]
@TheUntraceable close it

**Comment by nav-github01001** [comment]
Wow

**Comment by TheUntraceable** [comment]
Fixed in #49
