### ISSUE TITLE
Implement separate files

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#45]
## Description

Im just gonna be implementing separate files myself without circular import

## The problem

everything is stuffed in __init__.py 

## Checklist

- [ ] - You have checked that there is no issue already mentioning this feature, open or closed
- [x] - Full details of the requested feature have been provided/shown

**Comment by Jerrydotpy** [comment]
According to @TheUntraceable He will do this at March 30

**Comment by nav-github01001** [comment]
We are gradually doing this rn. Will be finished soon
