### ISSUE TITLE
`Client.commands`

### ISSUE THREAD

**Issue by TheUntraceable** [EpikCord/EpikCord.py#54]
### Summary

The command class needs a change.

### The Problem

So right now, the class was made **only** for Discord to construct, meaning that users can't use this class, we either can refactor it, or make a separate class for users to be able to access. 

### The Ideal Solution

To refactor the code.

### The Current Solution

Using requests ect.

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] Full details of the requested feature have been provided/shown

**Comment by Jerry-py** [comment]
I say use aiohttp

**Comment by Jerry-py** [comment]
Sourcery won't refactor that sorry

**Comment by Jerry-py** [comment]
R 7 referring to #11

**Comment by TheUntraceable** [comment]
> R u referring to #11

Nope, refactor as in change how it works.

**Comment by TheUntraceable** [comment]
> I say use aiohttp

I will ofc.

**Comment by TheUntraceable** [comment]
I'll make a `ClientApplicationCommand` class or somethin I'll see.
