### ISSUE TITLE
Implement SlashCommand

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#75]
### Summary

SlashCmnd

### The Problem

Discord API v9 deprecation & near deadline

### The Ideal Solution

Implement SlashCommand

- [x] add options 
- [x] add request to api for slashcmnd

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] Full details of the requested feature have been provided/shown

**Comment by Jerry-py** [comment]
We aren't even done with client, message, attachments yet so we can save this as a draft

**Comment by Jerry-py** [comment]
For later

**Comment by TheUntraceable** [comment]
I need a class for this, right now it's just a `dict`. It consists of `callback`, `name`, `description`, `options`.

**Comment by TheUntraceable** [comment]
I'll probably *try* to add some sort of `id` payload through caching it.

**Comment by Jerry-py** [comment]
Can't we try something like typing tuple of something

**Comment by TheUntraceable** [comment]
The only thing left in this is how we're calling the function, optional options won't work as of now, we *could* make every option need to be a `KWARG`, with a simple suffix of `, *,` in the function arguments like `async def ping(interaction, *, ...args)` meaning that we can call it with great ease.

**Comment by TheUntraceable** [comment]
Fixed
