### ISSUE TITLE
deprecate logging in console

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#76]
### Summary

It logs in console

### Reproduction Steps

Literally anything

### Minimal Reproducible Code

```python
Literally anything
```

### Expected Results

-

### Actual Results

logging in console

### Intents

Any

### System Information

-

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

**Comment by TheUntraceable** [comment]
What does it print?
