### ISSUE TITLE
Custom Emoji support

### ISSUE THREAD

**Issue by Jerry-py** [EpikCord/EpikCord.py#79]
### Summary

Custom emojis

### The Problem

We don't support custom emoji yet so might as well add that

### The Ideal Solution

We need to add if it is custom so make a property in emoji class called `is_custom` and `is_animated`

BTW custom Emoji is a str

### The Current Solution

Idk

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] Full details of the requested feature have been provided/shown

**Comment by Jerry-py** [comment]
I'll do this myself when I have time next week

**Comment by TheUntraceable** [comment]
So what is the difference between CustomEmojis and Emojis?

**Comment by Jerry-py** [comment]
Custom emoji are like: 
```
<a:name:id>
<:name:is>
```
