### ISSUE TITLE
Checklist in feature request

### ISSUE THREAD

**Issue by Jerry-py** [EpikCord/EpikCord.py#81]
### Summary

It isn't right the first 1

### The Problem

Irrelevant checkbox 

### The Ideal Solution

Replace it with something else

### The Current Solution

In ideal solution

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] Full details of the requested feature have been provided/shown

**Comment by Jerrydotpy** [comment]
Fixed Alr. Can close
