### ISSUE TITLE
Cannot handle lots of messages once

### ISSUE THREAD

**Issue by nav-github01001** [EpikCord/EpikCord.py#83]
### Summary

Cannot handle lots of messages once

### Reproduction Steps

Activate your bot and in a random channel in a server in which your bot is in, spam "example test" in my code
after 5 times. the bot shuts down

### Minimal Reproducible Code

```python
"""
Before you implement this in your bot, please note that its just for testing, 
If you have a test bot and are professional with your code, you can experiment 
with different features and report the bugs in an issue
"""


from EpikCord import Client,Intents,Messageable, Embed
import logging

intents = Intents().guilds.guild_members.guild_messages.direct_messages
logger = logging.getLogger('EpikCord')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(filename='.\\epik.log', encoding='utf-8', mode='w')
handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
logger.addHandler(handler)

client = Client("your_token", intents)

@client.event
async def message_create(message):
    if message.author.id == client.user.id:
        return
    if "example test" in message.content.lower():
        #message.channel = Messageable(client, message.channel_id)

        await message.channel.send(content="hello, chat testing", tts = True)

client.login()
```

### Expected Results

bot continues to work

### Actual Results

Task exception was never retrieved
future: <Task finished name='Task-1' coro=<WebsocketClient.login.<locals>.runner() done, defined at C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py:686> exception=ClientResponseError(RequestInfo(url=URL('https://discord.com/api/v9/channels/897720646463807501/messages'), method='POST', headers=<CIMultiDictProxy('Host': 'discord.com', 'Authorization': 'Bot ODk3MzU5ODgyNzY2OTIxNzI4.YWUhhA.9qsqSyRm-HrEvWuiKuHnCmbHhZg', 'User-Agent': 'DiscordBot (https://github.com/EpikCord/EpikCord.py 0.4.10)', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '__dcfduid=61daae92920a11ec8a9942010a0a09ac; __sdcfduid=61daae92920a11ec8a9942010a0a09ac311d8c1cbc28a387ae30dfeeec2558255d380c8675f55e3b5c1acd98f6bd12e9', 'Content-Length': '47', 'Content-Type': 'application/json')>, real_url=URL('https://discord.com/api/v9/channels/897720646463807501/messages')), (), status=429, message='Too Many Requests', headers=<CIMultiDictProxy('Date': 'Sun, 20 Feb 2022 05:04:03 GMT', 'Content-Type': 'application/json', 'Content-Length': '92', 'Connection': 'keep-alive', 'Retry-After': '3', 'x-ratelimit-scope': 'user', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-ratelimit-bucket': 'a06de0de4a08126315431cc0c55ee3dc', 'x-ratelimit-limit': '5', 'x-ratelimit-remaining': '0', 'x-ratelimit-reset': '1645333445.770', 'x-ratelimit-reset-after': '2.136', 'x-envoy-upstream-service-time': '9', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400', 'CF-Cache-Status': 'DYNAMIC', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=PtDr8S6LHBYVP9KvOx%2FDhQTRMKRRCpwdHJpLVyfvn9O7VgMsCJqjew1de8ZJq1p%2BMgTQJhlfEmP63%2FbHoOz0WoOkTbEeVlDHc90XlfwJg31Yetg8i2UER3wJs0yK"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '6e053125dc047574-KUL')>)>
Traceback (most recent call last):
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 688, in runner
    await self.connect()
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 630, in connect
    await self.handle_events()
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 387, in handle_events
    await self.handle_event(event["t"], event["d"])
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 444, in handle_event
    await event_func(data)
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 507, in message_create
    await self.events["message_create"](message)
  File "C:\FalconFiles\FalconTestVenv\Scripts\epfirstimp.py", line 27, in message_create
    await message.channel.send(content="hello, chat testing", tts = True)
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 334, in send
    response = await self.client.http.post(f"channels/{self.id}/messages", json=payload)
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\EpikCord\__init__.py", line 1264, in post
    return await super().post(f"{self.base_uri}/{url}", *args, **kwargs)
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\aiohttp\client.py", line 640, in _request
    resp.raise_for_status()
  File "C:\FalconFiles\FalconTestVenv\lib\site-packages\aiohttp\client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://discord.com/api/v9/channels/897720646463807501/messages')
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002484F4B7010>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 510, in _check_closed    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

### Intents

.guilds.guild_members.guild_messages.direct_messages

### System Information

Name: EpikCord.py
Version: 0.4.10
Summary: UNKNOWN
Home-page:
Author:
Author-email:
License: UNKNOWN
Location: c:\falconfiles\falcontestvenv\lib\site-packages
Requires: 
Required-by:

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

### Additional Context
I propose we send messages with a slight delay (0.5 - 1 sec) for time being and try to solve it

**Comment by TheUntraceable** [comment]
You rate limited yourself. Bad code issue. #4
