### ISSUE TITLE
No docs?

### ISSUE THREAD

**Issue by AndyIsHereBoi** [EpikCord/EpikCord.py#86]
### Summary

how do i know how to use it? i dont see anything

### Reproduction Steps

i use my eyes

### Minimal Reproducible Code

```python
none
```

### Expected Results

i expected to see examples or how to use it

### Actual Results

i see blank space

### Intents

none

### System Information

chrome

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

### Additional Context

none

**Comment by AndyIsHereBoi** [comment]
yes and yes because i want to know how to use it it seems like it covers alot of the api

**Comment by TheUntraceable** [comment]
![image](https://user-images.githubusercontent.com/73362400/155196546-dc659c12-07b8-4f4d-b913-cfc8ad912c55.png)

**Comment by TheUntraceable** [comment]
Give it a bit
I'll put up some examples.

**Comment by AndyIsHereBoi** [comment]
ok

**Comment by AndyIsHereBoi** [comment]
there should at least be some docs so new users can get started

**Comment by TheUntraceable** [comment]
The library isn't even complete yet. The library covers around 50% of the API. GIve it a while. We launch a stable release on March 1st.

**Comment by TheUntraceable** [comment]
if you really want join the Discord server and I'll answer your questions.

**Comment by nav-github01001** [comment]
I'll work on this
