### ISSUE TITLE
Inputting no token will result in no error

### ISSUE THREAD

**Issue by Jerry-py** [EpikCord/EpikCord.py#90]
### Summary

No token added into Client will raise no error

### Reproduction Steps

I wrote some code and ran it with no token and raises no error

### Minimal Reproducible Code

```python
-> __main__.py
from .bot import Bot

if __name__ == "__main__":
    Bot().login()


-> bot.py
from EpikCord import Client, Intents

class Bot(Client):
    def __init__(self, token: str):
        intents = Intents().all
        super().__init__(token, intents)

    async def on_ready(self):
        print("Ready")
```

### Expected Results

Raise an error having no token

### Actual Results

No error

### Intents

All - Intents().all

### System Information

```
Name: EpikCord.py
Version: 0.4.11
Summary: A Modern API wrapper for Discord, Intended for replacement of the now discontinued Discord.py library
Home-page: https://github.com/EpikCord/EpikCord.py
Author: EpikCord
Author-email:
License: MIT
Location: c:\users\jerry\appdata\local\programs\python\python310\lib\site-packages
Requires:
Required-by:
```

### Checklist

- [X] This bug was found on the latest version of EpikCord
- [X] You have checked that there is no issue already mentioning this bug, open or closed
- [X] Full details of the bug have been provided/shown, including full tracebacks in case of exceptions
- [X] All bot tokens have been hidden/omitted from any screenshots or code, if any

**Comment by Jerry-py** [comment]
If I add a token nothing still works

**Comment by Jerry-py** [comment]
Even if I tried the example way it doesn't work

**Comment by Jerry-py** [comment]
This source code is from github not from pypi

**Comment by Jerry-py** [comment]
Even from pypi it won't work. - It wont keep running

**Comment by nav-github01001** [comment]
Can you give me the logs please

**Comment by Jerry-py** [comment]
Wdym

**Comment by Jerry-py** [comment]
There's no output

**Comment by nav-github01001** [comment]
In the logs too ?

**Comment by TheUntraceable** [comment]
Great point.

**Comment by Jerry-py** [comment]
WDYM LOGS THERES NO LOGGING

**Comment by TheUntraceable** [comment]
There is Logging implemented in some classes. Not the Client class. I'm unsure as to why this isn't raising an error. It's a required argument...

**Comment by Jerry-py** [comment]
True

**Comment by nav-github01001** [comment]
Hmm

**Comment by Jerry-py** [comment]
This is an actual bug. 

1. The bot doesn't start 
2. No token will raise no error
